/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardInkItem: typeof import('./src/components/list/dashboard/DashboardInkItem.vue')['default']
    DashboardInkList: typeof import('./src/components/list/dashboard/DashboardInkList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputTag: typeof import('element-plus/es')['ElInputTag']
    ElLink: typeof import('element-plus/es')['ElLink']
    EllipseButton: typeof import('./src/components/button/EllipseButton.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FollowButton: typeof import('./src/components/FollowButton.vue')['default']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    ImageInk: typeof import('./src/components/list/ImageInk.vue')['default']
    InkCard: typeof import('./src/components/card/InkCard.vue')['default']
    InkCover: typeof import('./src/components/image/InkCover.vue')['default']
    InkDialog: typeof import('./src/components/InkDialog.vue')['default']
    InkForm: typeof import('./src/components/form/InkForm.vue')['default']
    InkIcon: typeof import('./src/components/icons/InkIcon.vue')['default']
    InkList: typeof import('./src/components/list/InkList.vue')['default']
    InkLogo: typeof import('./src/components/icons/InkLogo.vue')['default']
    InkNav: typeof import('./src/components/nav/InkNav.vue')['default']
    InkNavItem: typeof import('./src/components/nav/InkNavItem.vue')['default']
    InkPopover: typeof import('./src/components/popover/InkPopover.vue')['default']
    InkPreview: typeof import('./src/components/ink/InkPreview.vue')['default']
    InkSearch: typeof import('./src/components/InkSearch.vue')['default']
    InkUpload: typeof import('./src/components/upload/InkUpload.vue')['default']
    ItemListPopover: typeof import('./src/components/popover/ItemListPopover.vue')['default']
    LongInk: typeof import('./src/components/list/LongInk.vue')['default']
    MilkdownEditor: typeof import('./src/components/editor/milkdown/MilkdownEditor.vue')['default']
    MilkdownWrapper: typeof import('./src/components/editor/milkdown/MilkdownWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextPrompt: typeof import('./src/components/TextPrompt.vue')['default']
    ToolTip: typeof import('./src/components/editor/milkdown/ToolTip.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    UserItem: typeof import('./src/components/UserItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
